defaults:
  - default

strategy:
  _target_: lightning.pytorch.strategies.DDPStrategy
  # find_unused_parameters: false
  find_unused_parameters: true # in for unused vqvae and var
  gradient_as_bucket_view: true

accelerator: gpu
devices: -1
num_nodes: 1
sync_batchnorm: true
log_every_n_steps: 100 #20
